export { default as Navbar } from './Navbar';
export { default as Hero } from './Hero';
export { default as Intro } from './Intro';
export { default as Skills } from './Skills';
export { default as Services } from './Services';
export { default as Experience } from './Experience';
export { default as Projects } from './Projects';
export { default as Testimonials } from './Testimonials';
export { default as Contact } from './Contact';
